import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={`${inter.className} container`}>

        <div className="nav-container">
          <h1>NewBookStore</h1>
          <h3>The is one of the most exiting bookstore</h3>
        </div>
      
        {children}

        <div className="footer">copyright 2023</div>
        
        
      </body>
    </html>
  );
}
